### ISSUE TITLE
Prometheus errors in EKS with default configuration

### ISSUE THREAD

**Issue by dmitryax** [signalfx/splunk-otel-collector-chart#401]
Recent version of the helm chart installed with default configuration in EKS throws the following errors:

```
2022-03-08T04:28:31.722Z	error	prometheusexporter/prometheus.go:141	Could not get prometheus metrics	{"kind": "receiver", "name": "receiver_creator", "monitorType": "kubernetes-proxy", "error": "Get \"http://192.168.69.78:10249/metrics\": dial tcp 192.168.69.78:10249: connect: connection refused"}
```

k8s version: v1.21.5-eks-bc4871b

**Comment by dmitryax** [comment]
@jvoravong can you please take a look? Looks like caused by the latest changes for the control plane.

**Comment by jvoravong** [comment]
@dmitryax Thanks for reporting this. I originally assumed that pod labels were unique enough or that the managed kubernetes clusters didn't allow the k8s_observer to pick up on private control plane pods.
- This issue is present with EKS with only the proxy metrics.
- This issue is present on GKE with only the coredns metrics.
- This issue is not present on AKS.

It seems managed kubernetes clusters are trying to expose more control plane metrics in the long run which can cause more issues like this. The eks team is working on exposing proxy metrics (https://github.com/aws/containers-roadmap/issues/657).

Proposal:
We could use the .Values.distribution and some helper methods to know whether we should enable a control plane integrations by default. In the default values file we would leave the agent.controlPlaneMetrics subsection commented out and use this logic.
- If agent.controlPlaneMetrics.{component}.enabled=undefined, we enable the control plane metrics depending on what distribution is being used. The openshift and kubernetes other ("") distributions would have control plane metrics enabled by default while all other distributions would not.
- If agent.controlPlaneMetrics.{component}.enabled=true, the control plane component metrics are enabled.
- If agent.controlPlaneMetrics.{component}.enabled=false, the control plane component metrics are disabled.

Thoughts?

**Comment by dmitryax** [comment]
I think we should keep `enabled` as is, without an undefined state. Otherwise it makes it hard to understand the logic.

Why can't we figure out pod label based on the distribution?

**Comment by jvoravong** [comment]
We explicitly don't support EKS, GKE and AKS control plane metrics at this time. We could have

**Comment by dmitryax** [comment]
I would recommend just not setting up the control plane receivers for unsupported distributions as you suggested in the last snippet

**Comment by jvoravong** [comment]
@lindhe This helm chart does support collecting many metrics from AKS, but it specifically does not support collecting metrics the AKS control plane which is what [_otel-agent.tpl#L79](https://github.com/signalfx/splunk-otel-collector-chart/blob/splunk-otel-collector-0.45.0/helm-charts/splunk-otel-collector/templates/config/_otel-agent.tpl#L79) is referring to. Managed Kubernetes services such as AKS do not allow the user to access the control plane for metric collection.

**Comment by lindhe** [comment]
Alright, thanks for clarifying!

Is the first documentation I linked to out-of-date then?

**Comment by lindhe** [comment]
Hm... I'm sure it's just me missing the point here. But to me it looks like the documentation contradicts itself.

[Here](https://github.com/signalfx/splunk-otel-collector-chart/blob/440b2a13c1d228416e20608bc75bef4cece0a41b/docs/advanced-configuration.md?plain=1#L214-L222) it says:
```markdown
* Supported Distributions:
  * kubernetes 1.22 (kops created)
  * openshift v4.9
* Unsupported Distributions:
  * aks
  * eks
  * eks/fargate
  * gke
  * gke/autopilot
```

And [here](https://github.com/signalfx/splunk-otel-collector-chart/blob/440b2a13c1d228416e20608bc75bef4cece0a41b/docs/advanced-configuration.md?plain=1#L40-L51) it says:

```markdown
Use the `distribution` parameter to provide information about underlying
Kubernetes deployment. This parameter allows the connector to automatically
scrape additional metadata. The supported options are:

- `aks` - Azure AKS
- `eks` - Amazon EKS
- `eks/fargate` - Amazon EKS with Fargate profiles
- `gke` - Google GKE / Standard mode
- `gke/autopilot` - Google GKE / Autopilot mode
- `openshift` - Red Hat OpenShift
```


Is "the `distribution` parameter" referring to something other than the `distribution` field in `values.yaml`?
