### ISSUE TITLE
High increase in indexer queue used percentage when switching to otel

### ISSUE THREAD

**Issue by tqi-raurora** [signalfx/splunk-otel-collector-chart#503]
We've been using splunk connect for kubernetes for some time.
We've tried switching to otel, however when we switched we saw a considerable increase in the GBs ingested coming from kubernetes, along with a very big increase in the % used rate for the queues in our indexers.

We are wondering where this increase in indexer load might be coming from.

Here's a hypothesis: We've noted that otel by default sends some new metadada to splunk, in particular this field: k8s.container.restart_count

Is it possible that by trying to index k8s.container.restart_count or other metadata as an indexed field, splunk is suffering a higher load?
Is it possible to stop otel from sending metadata?

Thanks in advance

**Comment by atoulme** [comment]
Multiple things may contribute to a higher usage here.
We have identified that Splunk HEC exporter doesn't use multi-metrics events right now (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11459). It's also possible you get additional metrics as well since we can get more information from the cluster.
To disable metrics collection, we offer in our docs to set up `metricsEnabled` to false: https://github.com/signalfx/splunk-otel-collector-chart/blob/main/docs/advanced-configuration.md#disable-particular-types-of-telemetry

Please try this and let us know if it works for you.

**Comment by tqi-raurora** [comment]
@atoulme Thanks for your response!

Currently our configuration looks like:
metricsEnabled: false
tracesEnabled: false
logsEnabled: true

So it seems we are already using the suggested configuration

I wonder if we coud disable index-time field extractions from HEC metadata on the splunk side?

Other than that, I guess its possible the higher usage is coming from the increase in the volume of GBs ingested... But honestly the increase in volume is not that big, that's why I was thinking its more a issue of the 'quality' and not 'quantity' of the logs being ingested.

**Comment by matthewmodestino** [comment]
Could also be the chunk sizes and number of connections.

Can you give some detail about your Splunk deploy? Are the collectors being load balanced? etc

**Comment by atoulme** [comment]
Marking closed as inactive.
