### ISSUE TITLE
Possibility to use different HEC token per index.

### ISSUE THREAD

**Issue by Stiuil06** [signalfx/splunk-otel-collector-chart#646]
**What would you like to be added**:
We want to explicitly specify different HEC token for logs and metrics indexes.

**Why is this needed**:
Our splunk provider, provides as two indexes (*_events for logs and *_metrics for metrics) and we need to use different tokens.

**Comment by Stiuil06** [comment]
Hi @harshit-splunk could you help here? Maybe there is any other workaround to use different tokens?

**Comment by matthewmodestino** [comment]
We do not recommend this as it will create token sprawl and management nightmares.

We recommend one token per cluster and rely on the fact that we can route to different indexes by setting the index field with annotations or custom logic in a single log pipeline.

In order to achieve this you would have to have a different exporter for every token, which will not scale.

Happy to assist further to find a more scalable and manageable solution if you reach out to your Splunk account team they can find me.

**Comment by matthewmodestino** [comment]
Also after re-reading this we already provide the funtionality of sending logs to one index and metrics to another..again no need for multiple tokens as tokens are just a transport auth mechanism and dont dictate what index is used when sending the index in the hec event payload.

Just set the indexes u need here:

Events: https://github.com/signalfx/splunk-otel-collector-chart/blob/52d7534d220ab0b9a6703f3b7132a314beb807f5/helm-charts/splunk-otel-collector/values.yaml#L35

Metrics: https://github.com/signalfx/splunk-otel-collector-chart/blob/52d7534d220ab0b9a6703f3b7132a314beb807f5/helm-charts/splunk-otel-collector/values.yaml#L36

Then if further index overrides are needed see my previous comment.

**Comment by atoulme** [comment]
Closing as inactive. Please open a support case if you still need help.
