### ISSUE TITLE
Missing ServiceAccountName configuration for secret-splunk-validation-hook pod

### ISSUE THREAD

**Issue by philipsabri** [signalfx/splunk-otel-collector-chart#780]
### Describe the issue you're reporting

Hi, I believe we're missing the ``ServiceAccountName`` configuration for the  [secret-splunk-validation-hook pod](https://github.com/signalfx/splunk-otel-collector-chart/blob/main/helm-charts/splunk-otel-collector/templates/secret-splunk-validation-hook.yaml). Is there a reason it hasn't been added to the pod?

Since the  ``imagePullSecrets`` are [added to the ServiceAccount](https://github.com/signalfx/splunk-otel-collector-chart/blob/b36acaaa7b140170ea454ab905049c0f93e187cf/helm-charts/splunk-otel-collector/templates/serviceAccount.yaml#L3-L8), it would be helpful to use it on the hook pod when pulling the image from a private registry.

**Comment by jvoravong** [comment]
Sorry I didn't notice automation closed this ticket.

Updates:
- Verified in the latest version of OpenShift using the default service account works with the validation hook pod, I was concerned it wouldn't since they have higher security standards.
- Created the potential solution I was thinking of (link above) for this issue. While this solution would work I did find some drawbacks and don't think this is the way to go at this time. We might need it in the future.
- After more research, I do think we can go forward with the following fix.
  - Remove the service account in the validation hook
  - If the user provided [imagePullSecrets](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret), add them to the validation hook pod spec.
  -  @omrozowicz-splunk feel free to tackle this if you have time.
